Add coins
Adamant-im/adamant-wallets pull request #1
Opened 2022-09-22 12:05 UTC by confleux

2022-10-02 15:54 UTC, martiliones approved these changes

2022-10-05 16:43 UTC, bludnic requested changes

2022-10-05 16:43 UTC, bludnic commented on assets/general/adamant/info.json
> +}
No new line at end of the file. Same for other files.

2022-10-05 16:43 UTC, bludnic commented on assets/general/bitcoin/info.json
> +      {
Non consistent tabulation. Expected tab with 2 spaces instead of 4 spaces. Check other files as well.

2022-10-05 16:43 UTC, bludnic commented on assets/blockchains/ethereum/usds/info.json
> +  "id": "0xa4bdb11dc0a2bec88d24a3aa1e6bb17201112ebe",
Suggestion: rename property to `contractId` to be more descriptive

2022-10-05 16:43 UTC, bludnic commented on assets/general/dash/info.json
> +    "website": "https://dash.org/",
```suggestion
    "website": "https://dash.org",
```

2022-10-05 16:43 UTC, bludnic commented on assets/general/ethereum/info.json
> +    "website": "https://ethereum.org/",
```suggestion
    "website": "https://ethereum.org",
```

2022-10-05 16:43 UTC, bludnic commented on assets/general/lisk/info.json
> +    "website": "https://lisk.com/",
```suggestion
    "website": "https://lisk.com",
```

2022-10-05 16:43 UTC, bludnic commented on assets/general/usds/info.json
> +    "website": "https://stably.io/usds/",
```suggestion
    "website": "https://stably.io/usds",
```

2022-10-12 16:08 UTC, adamant-al commented on assets/general/bitcoin/info.json
> +  "fixedFee": 0.00003153,
BTC fee is calculated.
Add 0.00003153 as `defaultFee`.

2022-10-12 16:08 UTC, adamant-al commented on assets/general/lisk/info.json
> +  "fixedFee": 0.00142,
LSK fee is calculated.
Add 0.00142 as `defaultFee`.

2022-10-17 02:48 UTC, Andrey1029 approved these changes

2022-11-08 11:14 UTC, martiliones approved these changes

2022-11-08 15:07 UTC, adamant-al commented
See Readme for field description

2022-11-16 06:43 UTC, adamant-al commented
@bludnic @martiliones @Andrey1029 
Waiting for your reviews.

2022-11-16 13:28 UTC, bludnic commented on .gitignore
> +.vscode
please ignore also `.idea` directory (for Webstorm and IntelliJ IDEA users)

2022-11-16 20:02 UTC, martiliones requested changes

2022-11-17 09:35 UTC, adamant-al commented on assets/general/usds/info.json
> +  "explorer": "https://etherscan.io/token/0xa4bdb11dc0a2bec88d24a3aa1e6bb17201112ebe",
It's general info for Stably USD, and its token can be issued in different blockchains.
`explorerTx` and `explorerAddress` will be taken from `assets/blockchains/ethereum/info.json` ⟶ assets/general/ethereum/info.json` file.

2022-11-17 10:26 UTC, martiliones commented on assets/general/usds/info.json
> +  "explorer": "https://etherscan.io/token/0xa4bdb11dc0a2bec88d24a3aa1e6bb17201112ebe",
I thought about that but in the swagger API (#2) these properties are required.

> will be taken from `assets/blockchains/ethereum/info.json`...

then why is the `explorer` property there and not in ethereum's `info.json`?

2022-11-17 10:26 UTC, martiliones commented on assets/general/usds/info.json
> +  "explorer": "https://etherscan.io/token/0xa4bdb11dc0a2bec88d24a3aa1e6bb17201112ebe",
I thought about that but in the swagger API (#2) these properties are required.

> will be taken from `assets/blockchains/ethereum/info.json`...

then why is the `explorer` property there and not in ethereum's `info.json`?

2022-11-17 11:41 UTC, adamant-al commented on assets/general/ethereum/info.json
> +  "oldPendingTxFetchAttempts": 3,
I think it's a good idea.

2022-11-17 11:43 UTC, adamant-al commented on assets/general/usds/info.json
> +  "explorer": "https://etherscan.io/token/0xa4bdb11dc0a2bec88d24a3aa1e6bb17201112ebe",
It seems we better to rename `explorer` to `contractExplorer`

2022-11-17 11:45 UTC, adamant-al commented on assets/general/usds/info.json
> +  "explorer": "https://etherscan.io/token/0xa4bdb11dc0a2bec88d24a3aa1e6bb17201112ebe",
PR #2 will be changed as we'll finish with this one.

2022-11-17 19:03 UTC, martiliones commented on assets/general/bitcoin/info.json
> +    "newPendingTxFetchInterval": 10000,
remove `TxFetch` from inner property names to make them shorter which was main idea of grouping

2022-11-17 19:32 UTC, confleux commented on README.md
> +- `name` Readable coin name
cant fully comprehend what you are trying to say. could you explain it better to me?

2022-11-17 20:01 UTC, martiliones commented on README.md
> +- `name` Readable coin name
just use this format:
```jsonc
"propertyName": "example value" // Optional. Property description
```
For example:

```jsonc
{
  "name": "ADAMANT Messenger", // Readable coin name
  // ....
  "fixedFee": 0.5 // Optional. If to use fixed tx transfer fee
}
```

by the way the sentence "If to use fixed tx transfer fee" seems to be grammatically incorrect.

2022-11-18 05:43 UTC, adamant-al commented on README.md
> +- `name` Readable coin name
@martiliones Commit these changes by yourself and fix grammatical errors as well.

2022-11-22 09:57 UTC, adamant-al commented
@bludnic @martiliones I see you've "requested changes". Is there anything to resolve yet?
@Andrey1029 Still waiting for your review.

2022-11-22 09:58 UTC, adamant-al approved these changes

2022-11-22 10:21 UTC, martiliones commented
I wonder if "status" property could be replaced with `active: boolean`

2022-11-22 11:10 UTC, adamant-al commented
> I wonder if "status" property could be replaced with `active: boolean`

Currently, we'll stay with string, "active" or "disabled". I suppose there may be other values.

2022-11-25 12:45 UTC, martiliones approved these changes

2022-11-25 12:47 UTC, bludnic approved these changes

2022-11-28 04:34 UTC, Andrey1029 approved these changes

2022-11-28 04:40 UTC, Andrey1029 commented
Is it correct that bnb and usds doesnt contain `nodes` property?

2022-11-28 08:51 UTC, adamant-al commented
> Is it correct that bnb and usds doesnt contain `nodes` property?

Yes, as it uses Ethereum nodes.

2022-11-28 08:51 UTC, merged