Add ltcnode1.adm.im
Adamant-im/adamant-wallets pull request #105
Opened 2024-12-22 14:40 UTC by confleux

2024-12-23 00:27 UTC, bludnic requested changes

2024-12-23 00:27 UTC, bludnic commented on package-lock.json
> +{
Since we use PNPM there is no need to commit `package-lock.json`

2024-12-23 00:27 UTC, bludnic commented on package.json
> +  "packageManager": "pnpm@9.14.2+sha512.6e2baf77d06b9362294152c851c4f278ede37ab1eba3a55fda317a4a17b209f4dbb973fb250a77abc463a341fcb1f17f17cfa24091c4eb319cda0d9b84278387"
This will restrict the use of an exact version of PNPM. Better to remove it.

2024-12-23 00:27 UTC, bludnic commented on assets/general/ltc/info.json
> +{
Rename the folder from `/ltc` to `/litecoin` (similar as /adamant and /bitcoin)

2024-12-23 00:27 UTC, bludnic commented on assets/general/ltc/info.json
> +  "minBalance": 0.00000001,
Better to use a higher value to cover transaction fees.

```suggestion
  "minBalance": 0.001,
```

2024-12-23 00:31 UTC, bludnic commented
@confleux Ask the designer for images. See example: https://github.com/Adamant-im/adamant-wallets/tree/master/assets/general/bitcoin/images

2025-05-28 13:14 UTC, adamant-al commented
Not actual.

2025-05-28 13:14 UTC, closed without merging