Added adamant nodes
Adamant-im/adamant-wallets pull request #33
Opened 2023-06-19 13:05 UTC by StanislavDevIOS

Check this:
- https://news.adamant.im/roskomnadzors-attempt-to-censor-adamant-messenger-a-test-of-decentralization-c05711e8c865

1. Added new nodes: 
```
184.94.215.92, REST 45555, ws 45558
https://node1.adamant.business,/ wss 45558
https://node2.blockchain2fa.io,/ default ports
```
2. Added ip nodes for existing nodes that support http connection

2023-06-19 13:41 UTC, adamant-al requested changes
Add alternative IPs for nodes which have it:

```
{
  "url": "https://lake.adamant.im",
  "alt_ip": "149.102.157.15:36666"
}
```

2023-06-19 15:35 UTC, adamant-al requested changes
Add new info to the Readme.

2023-06-20 15:54 UTC, adamant-al approved these changes

2023-06-20 15:55 UTC, adamant-al requested changes
Change target branch to `dev`

2023-06-23 12:32 UTC, joebrock666 approved these changes

2023-06-24 09:10 UTC, adamant-al approved these changes

2023-06-28 08:27 UTC, merged