Added Verse token
Adamant-im/adamant-wallets pull request #42
Opened 2023-09-21 01:38 UTC by just-software-dev

Added Verse token

2023-09-21 10:40 UTC, adamant-al requested changes
Also

```
  "defaultVisibility": true,
  "defaultOrdinalLevel": 99,
```

See https://github.com/Adamant-im/adamant-wallets/pull/40/files

2023-09-21 10:40 UTC, adamant-al commented on assets/general/verse/info.json
> +  "name": "VERSE",
```suggestion
  "name": "Verse",
```

2023-09-22 02:44 UTC, just-software-dev commented
iOS tested, everything works

2023-09-22 08:13 UTC, adamant-al approved these changes

2023-09-22 11:26 UTC, adamant-al commented on assets/blockchains/ethereum/verse/info.json
> +  "defaultOrdinalLevel": 99,
```suggestion
  "defaultOrdinalLevel": 95,
```

2023-09-22 12:52 UTC, bludnic approved these changes

2023-09-22 13:21 UTC, confleux commented on assets/general/verse/info.json
> +      "url": "https://blog.bitcoin.com/"
```suggestion
      "url": "https://blog.bitcoin.com"
```

2023-09-22 14:00 UTC, adamant-al commented
@just-software-dev Merge it.

2023-09-25 11:45 UTC, merged