Add Tor configuration
Adamant-im/adamant-wallets pull request #47
Opened 2023-10-12 00:09 UTC by bludnic

### Checklist

- [ ] Add Tor nodes
- [ ] Add explorer URL for Tor
- [ ] Add infoService URL (also for Tor)
- [ ] Add `nodeMinVersion`
- [ ] Add `alt_ip` for Tor nodes and infoservice
- [ ] Add `website` for Tor

2023-10-12 00:11 UTC, bludnic commented
![](https://github.trello.services/images/mini-trello-icon.png) [Include tor nodes to adamant-wallets](https://trello.com/c/BIKZJ8ta/383-include-tor-nodes-to-adamant-wallets)

2023-10-14 09:05 UTC, adamant-al requested changes
We forger about coin tor nodes, add them.

2023-10-14 09:05 UTC, adamant-al commented on README.md
> +  // Optional. Services used by the project
```suggestion
  // Optional. Services related to a project
```

2023-10-14 09:05 UTC, adamant-al commented on README.md
> +  // Optional. Tor configuration if the project uses Tor
```suggestion
  // Optional. Tor configuration if a project uses Tor
```

2023-10-16 04:11 UTC, just-software-dev approved these changes

2023-10-16 04:12 UTC, just-software-dev approved these changes

2023-10-17 06:55 UTC, adamant-al approved these changes
- Suggest to set `minNodeVersion` to at least `0.7.0`.
- We suppose infoService's `alt_ip`'s default port is 80.
- Consider to add btcnode2 + alt_ip + tor, it's working
- Consider to add dogenode2 + alt_ip + tor, it's working
- Consider to add ethnode2 + alt_ip + tor, it's working
- Dash's node2 and node3 are on the way soon @confleux

2023-10-18 15:05 UTC, adamant-al commented
We can merge it.

2023-10-18 15:49 UTC, merged