Update alt_ip
Adamant-im/adamant-wallets pull request #56
Opened 2023-11-23 19:02 UTC by confleux

2023-11-25 10:56 UTC, adamant-al requested changes
- Update `infoService`
- Add `sunshine` node
- Add `alt_ip` for `node1.adamant.business`

2023-11-30 22:07 UTC, bludnic requested changes

2023-11-30 22:07 UTC, bludnic commented on assets/general/lisk/info.json
> +
extra breakline, prettify it

2023-11-30 22:07 UTC, bludnic commented on assets/general/lisk/info.json
> +
npx prettier . --write

2023-12-01 00:24 UTC, bludnic approved these changes

2023-12-08 23:16 UTC, adamant-al approved these changes

2023-12-09 02:17 UTC, bludnic commented
As we are migrating to Lisk v4, the old nodes (lisknode3, lisknode4) must be removed temporarily from the config. Same story for Lisk services.

After we release the PWA and iOS, we should update remaining nodes to the latest version and rollback the full list of nodes.

2023-12-18 13:23 UTC, adamant-al approved these changes
@confleux 
Changed dashnode1 IP. Does the port stay the same?

2023-12-18 13:23 UTC, adamant-al commented on assets/general/dash/info.json
> +      "alt_ip": "http://95.216.208.142:44099"
```suggestion
      "alt_ip": "http://45.85.147.224:44099"
```

2023-12-18 18:51 UTC, merged