Add storj
Adamant-im/adamant-wallets pull request #62
Opened 2024-01-10 15:37 UTC by confleux

2024-01-12 17:31 UTC, adamant-al approved these changes

2024-01-12 17:37 UTC, bludnic requested changes

2024-01-12 17:37 UTC, bludnic commented on assets/general/storj/info.json
> +      "name": "Reddit",
```suggestion
      "name": "reddit",
```

I saw before we used lowercase (e.g. for ethereum). Better to stick with one style

2024-01-12 17:40 UTC, bludnic approved these changes

2024-01-13 10:38 UTC, adamant-al commented
@confleux Merge it.

2024-01-18 08:59 UTC, merged