Chore/services
Adamant-im/adamant-wallets pull request #69
Opened 2024-01-31 02:24 UTC by confleux

2024-01-31 13:53 UTC, adamant-al commented
Updated description.

2024-03-12 07:05 UTC, bludnic requested changes

2024-03-12 07:05 UTC, bludnic commented on assets/general/ethereum/info.json
> +        "docs": "https://github.com/Adamant-im/ETH-transactions-storage?tab=readme-ov-file#api-request-examples"
Update the OpenAPI schema:

1. Create `ServiceDescription` in the [components](https://github.com/Adamant-im/adamant-wallets/blob/chore/services/specification/openapi.json#L8) section
2. Add the `ServiceDescription` component to [services](https://github.com/Adamant-im/adamant-wallets/blob/chore/services/specification/openapi.json#L243)

2024-03-12 07:09 UTC, bludnic commented on assets/general/ethereum/info.json
> +        "docs": "https://github.com/Adamant-im/ETH-transactions-storage?tab=readme-ov-file#api-request-examples"
It's important to keep the OpenAPI schema synced every time a new property is added. The PWA generates TS types from it.

2024-03-12 07:11 UTC, bludnic commented on assets/general/ethereum/info.json
> +        "docs": "https://github.com/Adamant-im/ETH-transactions-storage?tab=readme-ov-file#api-request-examples"
You can validate and visualise the schema on https://editor.swagger.io

2024-03-14 10:58 UTC, RealGoodProgrammer commented
This branch will be included in the next release

2024-06-06 18:50 UTC, bludnic commented
@confleux Merge `dev` and fix the conflicts. Resolve opened issues.

2024-06-06 19:13 UTC, adamant-al commented
Include new nodes and remove outdated.

2024-06-25 14:02 UTC, adamant-al commented
@confleux 

Merge dev and fix the conflicts. Resolve opened issues.
Update ethnodes, btcnodes.

2024-07-24 17:01 UTC, adamant-al commented
@bludnic @just-software-dev 
Review.

2024-09-06 20:55 UTC, bludnic approved these changes

2024-09-06 20:55 UTC, merged